"""menambahkan kolom no_hp ke tabel User

Revision ID: 1a05acc7fc8d
Revises: 6c87b6d9aa7e
Create Date: 2025-08-17 13:07:40.355176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a05acc7fc8d'
down_revision = '6c87b6d9aa7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_hp', sa.String(length=14), nullable=True))
        batch_op.create_unique_constraint(None, ['nomor_hp'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nomor_hp')

    # ### end Alembic commands ###
