"""Add pin_hash to users

Revision ID: 1cea2e655dd2
Revises: 1a05acc7fc8d
Create Date: 2025-08-17 13:57:35.594938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cea2e655dd2'
down_revision = '1a05acc7fc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    # ### end Alembic commands ###
