"""Menghapus kolom pin dari tabel users

Revision ID: 3542905b25da
Revises: 1cea2e655dd2
Create Date: 2025-08-17 14:01:03.812241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3542905b25da'
down_revision = '1cea2e655dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', mysql.VARCHAR(length=6), nullable=False))

    # ### end Alembic commands ###
