"""add price column to tables

Revision ID: 39788ca20aba
Revises: ed9b4b31c60c
Create Date: 2025-08-20 23:33:48.889466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39788ca20aba'
down_revision = 'ed9b4b31c60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
