"""Menambahkan role_id ke tabel users

Revision ID: 6c87b6d9aa7e
Revises: 04e787c896af
Create Date: 2025-08-14 19:42:29.362106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c87b6d9aa7e'
down_revision = '04e787c896af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
