"""Ubah Semua Tabel

Revision ID: ed9b4b31c60c
Revises: efd53ce09b1c
Create Date: 2025-08-19 23:15:44.649240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed9b4b31c60c'
down_revision = 'efd53ce09b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', mysql.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
