"""Add price column to Event model

Revision ID: ee4fc4ed1f19
Revises: 32284f36e36b
Create Date: 2025-08-12 15:03:41.944062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee4fc4ed1f19'
down_revision = '32284f36e36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
