"""Add arrival_time to Reservation table

Revision ID: fe20602300f7
Revises: e3e991375a68
Create Date: 2025-08-25 16:22:26.110277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe20602300f7'
down_revision = 'e3e991375a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('arrival_time')

    # ### end Alembic commands ###
